### ISSUE TITLE
Need to add "Read More" according to line number

### ISSUE THREAD

**Issue by vikskod** [devsideal/ReadMoreOption#1]
Please add "Read more" option according to the line number of TextView. Currently, it is only showing "Read more" option with respect to String length.

**Comment by devendroid** [comment]
good idea, i will add this option on the next update.

**Comment by devendroid** [comment]
Its done in version 1.0.1 , 
Now you can add "Read More" option according to line numbers using 
`.textLength(3, ReadMoreOption.TYPE_LINE) `
But also have a look [known issues ](https://github.com/devsideal/ReadMoreOption#known-issue) for some limitations.
